name: Setup
description: Common setup steps
inputs:
  lint:
    description: Lint sources
    required: false
    default: true
  token:
    description: GitHub token
    required: true
runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
    - name: Extend PATH
      shell: bash
      run: |
        echo "$GOPATH/bin" >>"$GITHUB_PATH"
    - name: Install Protoc
      uses: arduino/setup-protoc@v3
      with:
        repo-token: ${{ inputs.token }}
    - name: Download dependencies
      shell: bash
      run: |
        ./scripts/bootstrap.sh
    - name: Build sources
      shell: bash
      run: |
        mkdir bin
        go build -o ./bin main.go
    - name: Lint Go
      if: inputs.lint == 'true'
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.61.0
        args: --build-tags test --timeout=240s --verbose
