name: PR
on:
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: Lint
    timeout-minutes: 4
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Set up
        uses: ./.github/actions/setup
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  test:
    name: Test
    timeout-minutes: 3
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Set up
        uses: ./.github/actions/setup
        with:
          lint: false
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Test
        run: go test ./... -tags test -coverpkg=github.com/mtth/gitfetcher/internal -coverprofile=coverage.out -covermode=atomic
        env:
          SOURCES_GITHUB_TOKEN: ${{ secrets.SOURCES_GITHUB_TOKEN }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
      - name: Set up AsciiDoctor
        uses: reitzig/actions-asciidoctor@v2.0.2
        with:
          version: 2.0.18
      - name: Generate man page
        run: |
          asciidoctor -b manpage -d manpage docs/gitfetcher.adoc -o - \
            | gzip -9 >gitfetcher.1.gz
